project:
  type: website
  output-dir: docs

website:
  title: "CLS Group @ Plaksha"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub

format:
  html:
    theme: cosmo
    toc: true
    toc-title: "On this page"
    css: styles.css
    mainfont: "Segoe UI, sans-serif"